/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.ConexaoDAO;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.table.DefaultTableModel;
//import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author tf_noe
 */
public class FRM_Principal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRM_Principal.class.getName());

    /**
     * Creates new form FRM_Principal
     */
    public FRM_Principal() {
        initComponents();
        //lbl_usuario.setText("Olá " + nomeusuario);
        this.setLocationRelativeTo(null);
        // Pegar o usuário logado
        int idUsuarioLogado = Sessao.getIdUsuario();

        // Carregar os projetos desse usuário
        carregarProjetosUsuario(idUsuarioLogado);
    }

    public void setUsuario(String nomeUsuario) {
        lbl_usuario.setText("Olá " + Sessao.getNomeUsuario() + "!");

    }

    private void carregarProjetosUsuarioLogado() {
        int idUsuarioLogado = Sessao.getIdUsuario();
        carregarProjetosUsuario(idUsuarioLogado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        lbl_usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_projetos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Projetos");

        lbl_usuario.setText("Olá");

        jLabel2.setText("Veja seus projetos:");

        table_projetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Projeto", "Nome Projeto", "Data Início", "Data Fim"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_projetos);
        if (table_projetos.getColumnModel().getColumnCount() > 0) {
            table_projetos.getColumnModel().getColumn(0).setResizable(false);
            table_projetos.getColumnModel().getColumn(0).setPreferredWidth(2);
            table_projetos.getColumnModel().getColumn(1).setResizable(false);
            table_projetos.getColumnModel().getColumn(1).setPreferredWidth(300);
            table_projetos.getColumnModel().getColumn(2).setResizable(false);
            table_projetos.getColumnModel().getColumn(2).setPreferredWidth(50);
            table_projetos.getColumnModel().getColumn(3).setResizable(false);
            table_projetos.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        jMenu3.setText("Cadastro");

        jMenuItem1.setText("Cadastro Usuário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Projeto");

        jMenuItem2.setText("Gestão de Projetos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Gestão de Equipes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Gestão de Tarefas");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_usuario)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FRM_Usuario objusuario = new FRM_Usuario(this, true);
        objusuario.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void carregarProjetosUsuario(int idUsuarioLogado) {
        DefaultTableModel modelo = (DefaultTableModel) this.table_projetos.getModel();
        modelo.setRowCount(0); // sempre limpa antes de carregar

        String sql = "SELECT p.id_projeto, p.nm_projeto, p.dt_inicioprojeto, p.dt_fimprojeto "
                + "FROM tbl_projeto p "
                + "INNER JOIN tbl_projetousuario pu ON p.id_projeto = pu.id_projeto "
                + "WHERE pu.id_usuario = ?";

        try (java.sql.Connection conexao = new ConexaoDAO().conectaBD(); PreparedStatement stmt = conexao.prepareStatement(sql)){

            //banco = new ConexaoDAO().conectaBD();
            //pstm = banco.prepareStatement(sql); {
                
                
            stmt.setInt(1, idUsuarioLogado);

            try (ResultSet rs = stmt.executeQuery()) {
                boolean encontrou = false;

                while (rs.next()) {
                    encontrou = true;
                    modelo.addRow(new Object[]{
                        rs.getInt("id_projeto"),
                        rs.getString("nm_projeto"),
                        rs.getDate("dt_inicioprojeto"),
                        rs.getDate("dt_fimprojeto")
                    });
                }

                // se não encontrou nenhum projeto → limpa a grid
                if (!encontrou) {
                    modelo.setRowCount(0);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao carregar Projetos:\n" + e.getMessage(),
                    "Erro de Banco de Dados",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }


    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FRM_Projeto objprojeto = new FRM_Projeto(this, true);
        objprojeto.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FRM_EquipeProjeto objequipeprojeto = new FRM_EquipeProjeto(this, true);
        objequipeprojeto.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRM_Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable table_projetos;
    // End of variables declaration//GEN-END:variables
}
