/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import DAO.ConexaoDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author tf_noe
 */
public class FRM_EditaProjeto extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRM_EditaProjeto.class.getName());

    /**
     * Creates new form FRM_EditaProjeto
     */
    public FRM_EditaProjeto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public void receberDados(int id) {
        // Preenche os campos de texto com os dados do projeto
        String sql = "SELECT * FROM tbl_projeto WHERE id_projeto = ?";

        try (Connection conexao = new ConexaoDAO().conectaBD(); PreparedStatement stmt = conexao.prepareStatement(sql)) {

            stmt.setInt(1, id);

            try (ResultSet rs = stmt.executeQuery()) {

                if (rs.next()) {

                    this.txt_idprojeto.setText(String.valueOf(id));
                    this.txt_nmprojeto.setText(rs.getString("nm_projeto"));
                    this.txt_descricaoprojeto.setText(rs.getString("desc_projeto"));

                    java.sql.Date dtInicio = rs.getDate("dt_inicioprojeto");
                    java.sql.Date dtFim = rs.getDate("dt_fimprojeto");

                    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
                    if (dtInicio != null) {
                        this.txt_dtinicio.setText(sdf.format(dtInicio));
                    }
                    if (dtFim != null) {
                        this.txt_dtfim.setText(sdf.format(dtFim));
                    }

                } else {

                    JOptionPane.showMessageDialog(this, "Projeto com ID " + id + " não encontrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar dados do projeto:\n" + e.getMessage(), "Erro de Banco de Dados", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    //this.txt_idusuario.setText(String.valueOf(id)); // Converte o int 'id' para String
    //this.txt_nmusuario.setText(nome);

    ///this.cmb_tpacesso.setSelectedItem(tp_acesso);
        //this.txt_username.setText(user_name);
        //this.txt_emailusuario.setText(email_usuario);
        
        //if ("A".equals(statususuario)) {
        //    // Se o status for "A", MARCA a caixa de seleção.
        //    this.ck_ativo.setSelected(true);
        //} else {
        //    // Para qualquer outro status (como "I"), DESMARCA a caixa.
        //    this.ck_ativo.setSelected(false);
        //}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_idprojeto = new javax.swing.JTextField();
        txt_nmprojeto = new javax.swing.JTextField();
        txt_descricaoprojeto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_salvar = new javax.swing.JButton();
        txt_dtinicio = new javax.swing.JFormattedTextField();
        txt_dtfim = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Id Projeto:");

        txt_idprojeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idprojetoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Projeto:");

        jLabel3.setText("Descrição Projeto:");

        jLabel4.setText("Data Início:");

        jLabel5.setText("Data Fim:");

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        try {
            txt_dtinicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txt_dtfim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nmprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_dtinicio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_dtfim, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_salvar))
                            .addComponent(txt_descricaoprojeto))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_idprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nmprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_descricaoprojeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_dtinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_dtfim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_salvar))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idprojetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idprojetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idprojetoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        // 1. OBTER DADOS DA TELA
        String idStr = txt_idprojeto.getText();
        String nome = txt_nmprojeto.getText();
        String descricao = txt_descricaoprojeto.getText();
        String dataInicioStr = txt_dtinicio.getText();
        String dataFimStr = txt_dtfim.getText();

        // 2. VALIDAÇÃO BÁSICA
        if (nome.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo 'Nome Projeto' é obrigatório.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            txt_nmprojeto.requestFocus(); // Foca no campo para o usuário corrigir
            return; // Para a execução do método aqui
        }

        // 3. PARSE DE DATAS (Converter Texto para Objeto Date)
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        java.util.Date dataInicioUtil = null;
        java.util.Date dataFimUtil = null;

        try {
            // Apenas tenta converter se o campo não estiver vazio ou com a máscara
            if (!dataInicioStr.trim().replace("/", "").replace("_", "").isEmpty()) {
                dataInicioUtil = sdf.parse(dataInicioStr);
            }
            if (!dataFimStr.trim().replace("/", "").replace("_", "").isEmpty()) {
                dataFimUtil = sdf.parse(dataFimStr);
            }
        } catch (java.text.ParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de data inválido. Use o formato DD/MM/AAAA.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. LÓGICA DE INSERT VS UPDATE
        String sql;
        boolean isInsert = idStr.trim().isEmpty();

        if (isInsert) {
            // Novo projeto (INSERT)
            sql = "INSERT INTO tbl_projeto (nm_projeto, desc_projeto, dt_inicioprojeto, dt_fimprojeto) VALUES (?, ?, ?, ?)";
        } else {
            // Projeto existente (UPDATE)
            sql = "UPDATE tbl_projeto SET nm_projeto = ?, desc_projeto = ?, dt_inicioprojeto = ?, dt_fimprojeto = ? WHERE id_projeto = ?";
        }

        // 5. EXECUÇÃO NO BANCO DE DADOS
        try (java.sql.Connection conexao = new ConexaoDAO().conectaBD(); java.sql.PreparedStatement stmt = conexao.prepareStatement(sql)) {

            // Definir os parâmetros do PreparedStatement
            stmt.setString(1, nome);
            stmt.setString(2, descricao);

            // Parâmetro da Data de Início
            if (dataInicioUtil != null) {
                stmt.setDate(3, new java.sql.Date(dataInicioUtil.getTime()));
            } else {
                stmt.setNull(3, java.sql.Types.DATE);
            }

            // Parâmetro da Data de Fim
            if (dataFimUtil != null) {
                stmt.setDate(4, new java.sql.Date(dataFimUtil.getTime()));
            } else {
                stmt.setNull(4, java.sql.Types.DATE);
            }

            // Se for UPDATE, definir o ID no final da query
            if (!isInsert) {
                int id = Integer.parseInt(idStr);
                stmt.setInt(5, id);
            }

            // Executar a query
            int resultado = stmt.executeUpdate();

            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Projeto salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                this.dispose(); 
            }

        } catch (java.sql.SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar projeto no banco de dados:\n" + e.getMessage(), "Erro de Banco de Dados", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FRM_EditaProjeto dialog = new FRM_EditaProjeto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_descricaoprojeto;
    private javax.swing.JFormattedTextField txt_dtfim;
    private javax.swing.JFormattedTextField txt_dtinicio;
    private javax.swing.JTextField txt_idprojeto;
    private javax.swing.JTextField txt_nmprojeto;
    // End of variables declaration//GEN-END:variables
}
